@host=http://localhost:5000/api/v1



POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "johnny_man00753678",
  "password": "Ainguhonai5100"
}

###

POST {{host}}/login/two_factor HTTP/1.1
Content-Type: application/json

{
  "username": "johnny_man00753678",
  "totp_two_factor_on": false,
  "two_factor_identifier": "6fXIPB8Faum7mEactxXoVMePVSjuSVgOQEm9jOGsYhVtcR2er7R0tMVFu69z8Hn3",
  "verificationMethod": "1",
  "verificationCode": "123456"
}

###

GET {{host}}/unfollowers HTTP/1.1


###
GET {{host}} HTTP/1.1

###
POST {{host}}/logout HTTP/1.1
Content-Type: application/json


